### ISSUE TITLE
Make API end point to get csv. This means email and UI can get the same csv

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/india-api#15]
Make an end point that gets the forecast for the next day. 
The csv should have the following colums: 
- ts with timezone
- wind_kw
- solar_kw

The rows should be for every 15 mins

![Image](https://github.com/openclimatefix/india-api/assets/34686298/ba2e4d31-7bd0-4ca7-ad4d-c555b91f0cb9)

* depending on user requirements, this might change

**Comment by suleman1412** [comment]
hi @peterdudfield  I would like to work on this issue, can you please assign to me?

**Comment by peterdudfield** [comment]
It would be good to get generation and forecast in the csv

**Comment by suleman1412** [comment]
@peterdudfield does this involve referring to this endpoint? https://github.com/openclimatefix/india-api/blob/024963f9256b1052598d7253303b7218ce470b03/src/india_api/internal/service/server.py#L130

getting the data from this endpoint (based on the location entered by the user) and maybe converting it to a dataframe to download it as a csv?
