### ISSUE TITLE
Set up service to send csv via email, start with list of emails in the app, can upgrade later

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/india-api#16]
Set up service to send csv via email, 

This could be done in the API, if its easier

start with list of emails in the app (can upgrade later to make it more dynamic)

**Comment by peterdudfield** [comment]
We might be able to do this in the API - https://medium.com/nerd-for-tech/how-to-send-email-using-python-fastapi-947921059f0c

**Comment by peterdudfield** [comment]
how to attach a csv - https://stackoverflow.com/questions/77242491/how-to-send-email-with-attachment-in-fastapi-using-fastapi-mail-library

**Comment by aryanbhosale** [comment]
Hi @peterdudfield , is src/india_api/internal/service a good place to start by creating a new file where the service code will lie to send emails?

**Comment by peterdudfield** [comment]
Decided to not do this, so Ill close this now
