### ISSUE TITLE
remove the word 'yield'

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/india-api#21]
## Detailed Description
I find the world yield confusing, is it energy or %?

## Possible Implementation
rename variables

**Comment by rahul-maurya11b** [comment]
Hi @peterdudfield sir may I work on this?

**Comment by peterdudfield** [comment]
Yes please

**Comment by rahul-maurya11b** [comment]
@peterdudfield  :
 `PS D:\openclimate\india_api\india-api\india-api> india-api
Traceback (most recent call last):
  File "/usr/local/bin/india-api", line 5, in <module>
    from india_api.cmd.main import run
  File "/usr/local/lib/python3.11/site-packages/india_api/cmd/main.py", line 15, in <module>
    raise OSError(f"DB_URL env var is required using db source: {cfg.SOURCE}")
OSError: DB_URL env var is required using db source: indiadb`

what is the issue ?

**Comment by peterdudfield** [comment]
If you can use the dummy database https://github.com/openclimatefix/india-api/blob/main/src/india_api/cmd/main.py#L19, then it should run locally

**Comment by rahul-maurya11b** [comment]
@peterdudfield sir possible word changes can be : 
1. OUTPUT
2. ENERGY 
3. PRODUCTION
4. PERFORMANCE
5. GENERATION

out of these, I think energy or output is suitable for example in the context of these 2 examples : 

**Before**
1. Returns a list of predicted solar yields for a given location.
2. Returns a list of actual wind yields for a given location

**After**
1. Returns a list of predicted solar energy for a given location.
2. Returns a list of actual wind energy output for a given location
3. Returns a list of actual wind energy production for a given location

What are your thoughts?

**Comment by peterdudfield** [comment]
> @peterdudfield sir possible word changes can be :
> 
> 1. OUTPUT
> 2. ENERGY
> 3. PRODUCTION
> 4. PERFORMANCE
> 5. GENERATION
> 
> out of these, I think energy or output is suitable for example in the context of these 2 examples :
> 
> **Before**
> 
> 1. Returns a list of predicted solar yields for a given location.
> 2. Returns a list of actual wind yields for a given location
> 
> **After**
> 
> 1. Returns a list of predicted solar energy for a given location.
> 2. Returns a list of actual wind energy output for a given location
> 3. Returns a list of actual wind energy production for a given location
> 
> What are your thoughts?

Could we use `predicted solar power production` and similar for `wind` and `actual`

**Comment by rahul-maurya11b** [comment]
@peterdudfield  sir, please check #41. I have tested using Pytest and all tests are passing as before.
