### ISSUE TITLE
Cap numbers to zero

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/india-api#30]
Don't show anything below zero. Move any negative values up to 0

**Comment by Sohxn** [comment]
Hey, can I work on this ?

**Comment by peterdudfield** [comment]
yea sure
Would be good to do it in here https://github.com/openclimatefix/india-api/blob/main/src/india_api/internal/inputs/indiadb/client.py

and here https://github.com/openclimatefix/india-api/blob/main/src/india_api/internal/service/resample.py#L19

**Comment by DubraskaS** [comment]
Added changes to the line of code in resample that filters negative values so it is easier to read. Feedback advised.

Push done in the repo linked to the PR.

**Comment by peterdudfield** [comment]
Merged in #40
