### ISSUE TITLE
Cant use `pip install -e .` to run pytest

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/india-api#32]
@aryanbhosale

Do you want to add comments here on the problems you are having running pytest on this repo. 

Following from #28

**Comment by aryanbhosale** [comment]
##Here are the steps that I followed:

1. Cloned the repository: ```git clone https://github.com/openclimatefix/india-api.git``` 

2. Navigated to the root directory: ```cd india-api```

3. Created a virtual environment using venv: ```python -m venv .venv```

4. On windows: ```.venv\Scripts\activate```, On Linux: ```source .venv\Scripts\activate```

5. Followed the command mentioned in README: ```pip install -e .```

###Errors: 
C:\Users\aryan\AppData\Local\Programs\Python\Python312\include\pyconfig.h(59): fatal error C1083: Cannot open include file: 'io.h': No such file or directory
      error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2  
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pandas
Successfully built india-api
Failed to build pandas
ERROR: Could not build wheels for pandas, which is required to install pyproject.toml-based projects

**Comment by peterdudfield** [comment]
What about with python11

**Comment by aryanbhosale** [comment]
> What about with python11

Does any 3.11.x work? or a specific one?

**Comment by peterdudfield** [comment]
> > What about with python11
> 
> Does any 3.11.x work? or a specific one?

should be any

**Comment by aryanbhosale** [comment]
Okay I was finally able to install it, it was an issue with conflicting python versions which I resolved. But now in order to run ```india-api```, i need the ```DB_URL``` without which it throws this error:
OSError: DB_URL env var is required using db source: indiadb

apart from that, ```pytest``` is not a command, is there an alternative to this?

**Comment by aryanbhosale** [comment]
> Okay I was finally able to install it, it was an issue with conflicting python versions which I resolved. But now in order to run `india-api`, i need the `DB_URL` without which it throws this error: OSError: DB_URL env var is required using db source: indiadb
> 
> apart from that, `pytest` is not a command, is there an alternative to this?

Adding to this, I tried to find the test file and tried to run it by ```python .\src\india_api\internal\inputs\indiadb\conftest.py```
but got the error: 
ModuleNotFoundError: No module named 'pytest'

**Comment by aryanbhosale** [comment]
> > Okay I was finally able to install it, it was an issue with conflicting python versions which I resolved. But now in order to run `india-api`, i need the `DB_URL` without which it throws this error: OSError: DB_URL env var is required using db source: indiadb
> > apart from that, `pytest` is not a command, is there an alternative to this?
> 
> Adding to this, I tried to find the test file and tried to run it by `python .\src\india_api\internal\inputs\indiadb\conftest.py` but got the error: ModuleNotFoundError: No module named 'pytest'

I installed ```pytest``` by ```pip install -U pytest``` and tried to run ```python .\src\india_api\internal\inputs\indiadb\conftest.py``` again, but now I see ```ModuleNotFoundError: No module named 'testcontainers'``` error, which I solved by ```pip install testcontainers```

**Comment by peterdudfield** [comment]
and can you run `pytest`?

**Comment by aryanbhosale** [comment]
> and can you run `pytest`?

It says that pytest is not a command

**Comment by peterdudfield** [comment]
you need to install pytest, `pip install pytest` should do it

**Comment by aryanbhosale** [comment]
2 of the 14 cases are failing when i run ```pytest```
![image](https://github.com/openclimatefix/india-api/assets/36108149/33c3f9b0-a2f7-4368-b4c3-4c9a5a2c1b9d)
![image](https://github.com/openclimatefix/india-api/assets/36108149/acdc0012-a6e1-4328-ab82-2ca1c5eb7cc2)

**Comment by aryanbhosale** [comment]
> 2 of the 14 cases are failing when i run `pytest` ![image](https://private-user-images.githubusercontent.com/36108149/314616626-33c3f9b0-a2f7-4368-b4c3-4c9a5a2c1b9d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA5NTg1NDQsIm5iZiI6MTcxMDk1ODI0NCwicGF0aCI6Ii8zNjEwODE0OS8zMTQ2MTY2MjYtMzNjM2Y5YjAtYTJmNy00MzY4LWI0YzMtNGM5YTVhMmMxYjlkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIwVDE4MTA0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYyODhiMjY3MzAwNGIzNTY5YzAzMzU4Y2Y4MDdiZmFkZDI2YWIyMDQ5NmMzZWIzOTA1MTVjZjZlYjA0NGRhMzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.x36m4iWVC9RpT71SFdeuiyb40shFFrnRp9V_g8O5zQY) ![image](https://private-user-images.githubusercontent.com/36108149/314617242-6ffbd508-12d4-4014-b340-f69966ce142c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA5NTg1NDQsIm5iZiI6MTcxMDk1ODI0NCwicGF0aCI6Ii8zNjEwODE0OS8zMTQ2MTcyNDItNmZmYmQ1MDgtMTJkNC00MDE0LWIzNDAtZjY5OTY2Y2UxNDJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIwVDE4MTA0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVhZmIzOWUzZmZkMTgyZDFjNmUyZWE2MTE0MzUwNzBmNDQ5NDIyNDkzZjUxMzMzOTk5NTgzYWZlNmZmMWM5YjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TWnLKcjWU8BYnL9bASOs6U-jKcVbWwuyVmHzNhzzDzY)

I mightve added a fix for this in #33 , could you please check?

**Comment by peterdudfield** [comment]
What was the solution here? Should we add anything to the readme.md?

**Comment by aryanbhosale** [comment]
> What was the solution here? Should we add anything to the readme.md?

I think using Linux(dual boot,vm,or wsl) is the only solution in this case, should I add it at the start of the readme?

**Comment by peterdudfield** [comment]
i think it works on my mac, but perhaps yea good to create a section called known bugs. And say there may be some errors when isntalling this on windows

**Comment by aryanbhosale** [comment]
> i think it works on my mac, but perhaps yea good to create a section called known bugs. And say there may be some errors when isntalling this on windows

Alright I'll do that, got a test right now :/
Will do it after that

**Comment by aryanbhosale** [comment]
I've made the changes in the docs here #39
