### ISSUE TITLE
Add region search too when getting sites

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/india-api#81]
When loading ruvnl sites, only load ruvnl sites. Current it loads the first pv / wind site there is

https://github.com/openclimatefix/india-api/blob/main/src/india_api/internal/inputs/indiadb/client.py#L94

For the moment we got round this by making sure ad sites are second in the list, by uuid

**Comment by anxkhn** [comment]
This issue seems to be resolved. Please close this issue @peterdudfield
