### ISSUE TITLE
make sure api doesnt load the results - initially

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/india-api#97]
Some sites will now have multi models, this could be due to mulit models, or adjuster

We need the api to load the correct model, or the one we want it too. 

Two ideas
- Some how in database label the model as the one we are using, this could be `ml_model_name` in the site or something like that. Note new models are made with new versions
- hard code values (or env var) which model to load in api

**Comment by devsjc** [comment]
When we produce a forecast, it is produced by a specific model right? And also each forecast is produced for a specific site. So I don't think we should have any kind of model data on the site itself - it's only relevant data to the forecast. I'm pretty sure we already have a model name or version in the forecast table, so it should be a matter of for the site in question, find forecasts for that site, then select the ones based on the desired model. So it would be part of the GET request for forecast values for a site (we'd probably want a new endpoint which also just lists the model names so we can find out what is available).

**Comment by peterdudfield** [comment]
Yea, thats all true. I think the hard thing is when there are two models, we need to say which model to load. One of the those models should be default, as (I think) we don't need the users to know this. The default model is what I'm thinking about, perhaps we hard code that as a default for the moment
